version: "3.9"

services:
  bot:
    image: node:20
    container_name: telegram-bot-dev
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./prisma:/app/prisma
    environment:
      DATABASE_URL: postgres://andreyysak:puma4774@db:5432/dashboard_db
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      NODE_ENV: development
    command: sh -c "npm install && npx ts-node-dev --respawn src/index.ts"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: telegram-bot-db-1
    environment:
      POSTGRES_USER: andreyysak
      POSTGRES_PASSWORD: puma4774
      POSTGRES_DB: dashboard_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
